channels:
        - conda-forge
        - defaults
dependencies:
        - python=2.7
        - ferret_datasets
        - pyferret
        - pandas
        - numpy
        - pip:
                - ferretmagic==2016.10.28 
