name: ferretmagic
channels:
  - conda-forge
  - r
dependencies:
  - python=3.7
  - jupyter
  - notebook
  - numpy
  - pandas
  - bokeh
  - pyferret
  - ferret_datasets
  - rpy2
  - pip
  - pip:
    - ipywidgets
    - randomcolor
    - ferretmagic
